License key
arangodb/docs pull request #1011
Opened 2022-06-02 12:45 UTC by nerpaula

- added info about license key when upgrading to Enterprise edition
- added info about license key for Kubernetes deployments

2022-06-02 18:57 UTC, Simran-B requested changes

2022-06-03 05:56 UTC, nerpaula commented on 3.7/deployment-kubernetes-usage.md
>  For example (all examples can be found [in the kube-arangodb repository](https://github.com/arangodb/kube-arangodb/tree/master/examples){:target="_blank"}):
For some reason, the checks have failed after applying this suggestion.

2022-06-03 06:05 UTC, Simran-B commented on 3.7/deployment-kubernetes-usage.md
>  For example (all examples can be found [in the kube-arangodb repository](https://github.com/arangodb/kube-arangodb/tree/master/examples){:target="_blank"}):
```
/opt/build/repo/_plugins/versions/version.rb:45:in `<=>': undefined method `version' for nil:NilClass (NoMethodError)
```
This error occurs every so often, not sure why, but it has nothing to do with the content changes. You can push an empty commit (`git commit --allow-empty -m "Re-trigger Netlify"`) which should fix it.

2022-06-03 07:14 UTC, Simran-B approved these changes

2022-06-07 10:03 UTC, joerg84 approved these changes
Thanks! Overall great, just left minor comments.

2022-06-07 10:03 UTC, joerg84 commented on 3.7/deployment-kubernetes-usage.md
> +After deploying the latest ArangoDB Kubernetes operator, use the command below to deploy your license key as a secret:
Should mention it is EE only, not community

2022-06-07 10:03 UTC, joerg84 commented on 3.7/deployment-kubernetes-usage.md
> +After deploying the latest ArangoDB Kubernetes operator, use the command below to deploy your license key as a secret:
And potentially a link to general LK documentation

2022-06-07 10:03 UTC, joerg84 commented on 3.7/deployment-kubernetes-usage.md
> +Additionally, you can specify:
Again just a quick note on EE only

2022-06-07 10:03 UTC, joerg84 commented on 3.9/upgrading-community-to-enterprise.md
> +The Enterprise Edition of ArangoDB requires a license to activate the Enterprise Edition features.
Technically it is not just about activating the features, but running EE (i.e., an EE without a license key does not just become a community version, but does not run at all)

2022-06-07 14:19 UTC, merged