kube-arangodb: Use arm64 architecture for deployment
arangodb/docs pull request #1178
Opened 2022-11-10 07:46 UTC by Simran-B

2022-11-10 08:38 UTC, jwierzbo requested changes

2022-11-10 08:38 UTC, jwierzbo commented on 3.10/deployment-kubernetes-deployment-resource.md
> +To let new members as well as recreated members use `arm64` nodes, modify the
I guess we should link/mention here that this has to be enabled in the operator first (as described above)

2022-11-10 08:38 UTC, jwierzbo commented on 3.10/deployment-kubernetes-usage.md
> +Use at least version 1.2.19 of the operator.
1.2.20

2022-11-10 08:47 UTC, jwierzbo approved these changes

2022-11-15 05:00 UTC, nerpaula approved these changes
LGTM

2022-11-15 05:06 UTC, merged