ArangoSearch - Achieve stable pagination
arangodb/docs pull request #1275
Opened 2023-02-17 08:15 UTC by nerpaula

2023-02-20 12:02 UTC, Simran-B requested changes

2023-02-20 12:02 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +- the SORT operation must have at least one unique field to sort by
```suggestion
- the `SORT` operation must have at least one field with a unique value to sort by
```

2023-02-20 12:02 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +then this field should be used in the SORT operation as a tiebreaker. If there
```suggestion
then this field should be used in the `SORT` operation as a tiebreaker. If there
```

2023-02-20 12:02 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +is no such field, you can use the `_id` system field as it is unique and
```suggestion
is no such field, you can use the `_id` system attribute as it is unique and
```

2023-02-20 12:02 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +  LIMIT 10,20
```suggestion
  LIMIT 10, 20
```

2023-02-20 14:31 UTC, Dronplane approved these changes
LGTM. But I'd suggest to have a more detailed example with dataset,

2023-02-23 08:18 UTC, nerpaula commented
Added an example with dataset, thanks @Simran-B for helping out with this.

2023-02-23 08:59 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +- the `SORT` operation must have at least one field with an unique value to sort by
Sentence style?
```suggestion
- The dataset should not be changed.
- The `SORT` operation must have at least one field with an unique value to sort by.
```
Should we point out that even if the dataset doesn't change that you can get an unstable order with pagination? It's not so clear what the first point is supposed to say.

2023-02-23 09:06 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +  RETURN doc
I don't like that we start with this "free-floating" example and then switch to another one. I think we should show the full final example here instead, and possibly add a comment after `doc._id` to emphasize it.

2023-02-23 09:06 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +If you change the query to `LIMIT 5, 5`, then you get:
```suggestion
If you change the query to `LIMIT 5, 5` to get the next few results, then you get:
```

2023-02-23 09:15 UTC, Simran-B commented on 3.10/arangosearch-ranking.md
> +Teenage Mutant Ninja Turtles II: The Secret of the Ooze.
We did not see the TMNT result with the score so far! And I would also mention that Batman Begins appears twice, which is the result of the unstable sort, but it wouldn't hurt to also explain the outcome from a user PoV.

2023-02-24 10:49 UTC, Simran-B approved these changes

2023-02-24 10:56 UTC, merged