BM25() text length scaling 0..1
arangodb/docs pull request #1356
Opened 2023-05-03 13:08 UTC by Simran-B

The 3rd parameter `b` of `BM25()` has no range limitation, but the formula only works only if it is between 0 and 1 (inclusive). Setting it to something outside of the bounds yields undefined results. 

This is especially important if yu use the WAND optimization, which makes results even more undefined. E.g. if we use b = 4, better docs might start having negative score values. That would be correct computationally but totally misleading for end-user.

2023-05-03 13:09 UTC, MBkkt approved these changes

2023-05-03 16:16 UTC, MBkkt requested changes
Could you also point about same issue for `k < 0`

2023-05-04 06:38 UTC, Simran-B commented
@MBkkt Added a similar remark about the text term frequency scaling value

2023-05-04 08:17 UTC, MBkkt approved these changes

2023-05-04 08:55 UTC, Simran-B commented on 3.10/aql/functions-arangosearch.md
> +  The value needs to be `0.0` or higher, or the returned score is an
@MBkkt Can `-0.0` cause trouble?

2023-05-08 04:51 UTC, nerpaula approved these changes

2023-05-08 04:51 UTC, merged