DOC-352 | Auto login to database UI
arangodb/docs pull request #1358
Opened 2023-05-05 05:35 UTC by nerpaula

Added documentation for the auto login feature from ArangoGraph to database UI.

2023-05-10 07:23 UTC, Robert-Stam commented on arangograph/deployments.md
> +your ArangoDB deployment. This feature can be disabled at any time.
IMO we should describe something about:
1) permissions (currently we have full-access and read-only)
2) that it's available on port 8529 only (not 18529, which is for drivers). 

Limitations:
port 8529 will be technically switched from tcp to http mode, which means that velocy-stream cannot be used, so if drivers are (by accident) using port 8529 this will be a breaking change.

2023-05-10 07:25 UTC, Robert-Stam reviewed
See comments, sorry for the delay (I was on holidays)

2023-05-11 09:56 UTC, nerpaula commented on arangograph/deployments.md
> +your ArangoDB deployment. This feature can be disabled at any time.
Thanks, added this information.

2023-05-17 15:03 UTC, mattcarabine requested changes

2023-06-05 09:00 UTC, nerpaula commented on arangograph/deployments.md
> +your ArangoDB deployment. This feature can be disabled at any time.
Added.

2023-06-19 09:17 UTC, mattcarabine approved these changes

2023-06-22 07:26 UTC, merged