DOC-468 | ArangoSearch Views building in progress query warning
arangodb/docs pull request #1361
Opened 2023-05-09 05:19 UTC by nerpaula

2023-05-09 07:47 UTC, Simran-B requested changes
@MBkkt Just to double check, with inverted indexes / search-alias Views, you never see incomplete results?

2023-05-09 07:47 UTC, Simran-B commented on 3.11/arangosearch.md
> +query includes an `1240` warning message informing you that the `arangosearch`
```suggestion
query includes a warning message (code `1240`) informing you that the `arangosearch`
```

2023-05-09 07:47 UTC, Simran-B commented on 3.11/release-notes-api-changes311.md
> +warning. This warning alerts you about potentially incomplete results obtained
```suggestion
against this View while it is still being indexed, you now receive the query result
including a warning. This warning alerts you about potentially incomplete results obtained
```

2023-05-09 07:47 UTC, Simran-B commented on 3.11/release-notes-api-changes311.md
> +When using the `db._query` method to execute an AQL query against an
```suggestion
When you use the `db._query()` method to execute an AQL query against an
```

2023-05-09 07:47 UTC, Simran-B commented on 3.11/release-notes-api-changes311.md
> +complete due to the ongoing building process of the View.
```suggestion
complete due to the ongoing indexing process of the View.
```

2023-05-09 07:47 UTC, Simran-B commented on 3.11/release-notes-api-changes311.md
> +the query now includes a warning message that the result set may not be
```suggestion
the query now includes a warning message that the results may not be
```

2023-05-09 07:47 UTC, Simran-B commented on 3.12/arangosearch.md
> +query includes an `1240` warning message informing you that the `arangosearch`
```suggestion
query includes a warning message (code `1240`) informing you that the `arangosearch`
```

2023-05-09 07:47 UTC, Simran-B commented on 3.11/release-notes-api-changes311.md
> +### Query methods
```suggestion
### Query method
```

2023-05-09 10:56 UTC, MBkkt commented
> Just to double check, with inverted indexes / search-alias Views, you never see incomplete results?

Yes, because index invisible for user while it's building

2023-05-11 08:21 UTC, hkernbach approved these changes

2023-05-11 09:57 UTC, merged