Weighted Traversal
arangodb/docs pull request #558
Opened 2020-09-28 14:22 UTC by maierlars

ArangoDB PR: https://github.com/arangodb/arangodb/pull/12205

2020-10-01 12:25 UTC, Simran-B commented
Reminder to self: see comment https://github.com/arangodb/arangodb/pull/12205#issuecomment-683741662

2020-10-02 13:01 UTC, mchacki requested changes
The documentation it self is good!

We should add it in the document of "New Features 3.8" as well.

2020-10-02 14:52 UTC, mchacki approved these changes
LGTM

2020-10-07 16:23 UTC, Simran-B approved these changes

2020-10-07 16:27 UTC, merged