Examples added to Document Function in docs
arangodb/docs pull request #817
Opened 2021-11-16 16:41 UTC by santanu82021

2021-12-09 09:02 UTC, ansoboleva requested changes

2021-12-09 09:04 UTC, ansoboleva commented on 3.10/aql/functions-miscellaneous.md
> +{% include aqlexample.html id=examplevar type=type query=query bind=bind result=result %}
@santanu82021 Please add a line break between different docublocks.

2021-12-13 09:51 UTC, ansoboleva approved these changes
reviewed

2021-12-13 09:52 UTC, merged

2021-12-15 14:57 UTC, cw00dw0rd commented
To fix this a dataset is needed in the docublock, [described here](https://github.com/arangodb/docs#adding-a-new-aql-example):
`@DATASET{name_of_dataset}` the `knows_graph` results in `_id` values such as `persons/alice` which can be used in the `DOCUMENT()` function.