document SHARD_ID
arangodb/docs pull request #859
Opened 2022-01-04 15:11 UTC by kvahed

2022-01-04 16:15 UTC, santanu82021 reviewed
Looks good to me.

2022-01-05 11:15 UTC, joerg84 commented
Upstream PRs: 
devel https://github.com/arangodb/arangodb/pull/15428
3.9 https://github.com/arangodb/arangodb/pull/15430
3.8 https://github.com/arangodb/arangodb/pull/15431

2022-01-10 15:51 UTC, KVS85 requested changes
Need live examples.

2022-01-10 18:00 UTC, KVS85 approved these changes
LGTM.

2022-01-11 08:35 UTC, ansoboleva approved these changes
reviewed

2022-01-11 08:41 UTC, joerg84 approved these changes

2022-01-11 08:41 UTC, joerg84 commented on 3.10/aql/functions-miscellaneous.md
> +### SHARD_ID()
Should this be mentioned in the changelog/what is new section as well?

2022-01-11 13:23 UTC, merged