docs PR for https://github.com/arangodb/arangodb/pull/16181
arangodb/docs pull request #994
Opened 2022-05-17 15:09 UTC by jsteemann

2022-05-19 06:58 UTC, neunhoef approved these changes
LGTM. One typo suggested to correct.

2022-05-19 06:58 UTC, neunhoef commented on 3.10/release-notes-api-changes310.md
> +between two calls: if `phase`, feature` and `recoveryTick` don't change, then there hasn't
```suggestion
between two calls: if `phase`, `feature` and `recoveryTick` don't change, then there hasn't
```

2022-05-20 08:51 UTC, Simran-B requested changes
The last bullet point needs to be adjusted accordingly:
https://github.com/arangodb/docs/blob/feature/open-http-interface-earlier/3.10/http/general.md#error-handling

2022-05-20 08:51 UTC, Simran-B commented on 3.10/http/general.md
> +late, after the recovery was finished.
It's not necessarily clear to users what the recovery is and that it's always run, not just after a crash.

2022-05-20 08:51 UTC, Simran-B commented on 3.10/release-notes-api-changes310.md
> +between two calls: if `phase`, feature` and `recoveryTick` don't change, then there hasn't
```suggestion
between two calls: if `phase`, `feature` and `recoveryTick` don't change, then there hasn't
```

2022-05-20 08:51 UTC, Simran-B commented on 3.10/release-notes-api-changes310.md
> +  "in prepare", "in start", "in wait", "in shutdown", "in stop" or "in unprepare".
```suggestion
  `"in prepare"`, `"in start"`, `"in wait"`, `"in shutdown"`, `"in stop"`, or `"in unprepare"`.
```

2022-05-20 08:51 UTC, Simran-B commented on 3.10/release-notes-api-changes310.md
> +  "in prepare", "in start", "in wait", "in shutdown", "in stop" or "in unprepare".
```suggestion
  `"in prepare"`, `"in start"`, `"in wait"`, `"in shutdown"`, `"in stop"`, or `"in unprepare"`.
```

2022-05-20 08:51 UTC, Simran-B commented on 3.10/release-notes-api-changes310.md
> +between two calls: if `phase`, feature` and `recoveryTick` don't change, then there hasn't
```suggestion
between two calls: if `phase`, `feature` and `recoveryTick` don't change, then there hasn't
```

2022-06-23 08:07 UTC, Simran-B commented
@joerg84 I'm not sure what you try to say. This PR is blocked by https://github.com/arangodb/arangodb/pull/16381 as indicated by the updated description.

2022-06-29 08:40 UTC, ansoboleva commented
https://jenkins.arangodb.biz:3456/view/Documentation/job/arangodb-ANY-examples/2132/

2022-06-29 09:21 UTC, merged